#
# Ci-dessous la config qui permet de déployer le site web de la politique informatique de l'Abes
#
# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#

services:

  abes-politique-informatique:
    image: abesesr/abes-politique-informatique:${ABES_POLITIQUE_INFORMATIQUE_VERSION}
    container_name: abes-politique-informatique
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    environment:
      ABES_POLITIQUE_INFORMATIQUE_HTTP_BASEURL: ${ABES_POLITIQUE_INFORMATIQUE_HTTP_BASEURL}
    ports:
      - ${ABES_POLITIQUE_INFORMATIQUE_HTTP_PORT}:80
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=abes-politique-informatique"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=nginx"
      # pour que les mises à jour de cette image soient auto-déployées par watchtower
      - "com.centurylinklabs.watchtower.scope=abes-politique-informatique-watchtower-scope"





  #######################################
  # abes-politique-informatique-watchtower
  abes-politique-informatique-watchtower:
    image: nickfedor/watchtower:1.13.1
    container_name: abes-politique-informatique-watchtower
    restart: unless-stopped
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_LIMIT}
    cpus: ${CPU_LIMIT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 60
      WATCHTOWER_DEBUG: "false"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_WARN_ON_HEAD_FAILURE: "never"
      WATCHTOWER_RUN_ONCE: ${ABES_POLITIQUE_INFORMATIQUE_WATCHTOWER_RUN_ONCE}
      WATCHTOWER_NOTIFICATIONS: "slack"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: ${ABES_POLITIQUE_INFORMATIQUE_WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL}
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: ${ABES_POLITIQUE_INFORMATIQUE_WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER}
      WATCHTOWER_NOTIFICATION_SLACK_CHANNEL: "#notif-polinfo"
      WATCHTOWER_SCOPE: "abes-politique-informatique-watchtower-scope"
      REPO_USER: ${ABES_POLITIQUE_INFORMATIQUE_WATCHTOWER_DOCKERHUB_USER}
      REPO_PASS: ${ABES_POLITIQUE_INFORMATIQUE_WATCHTOWER_DOCKERHUB_PASS}
    labels:
      - "com.centurylinklabs.watchtower.scope=abes-politique-informatique-watchtower-scope"



